name: CI

env:
  CI: true

on:
 push:

jobs:
 CI:
   runs-on: ubuntu-latest
   steps:
    - name: checkout
      uses: actions/checkout@v2
    
    # Nodeのバージョンを指定
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
        registry-url: https://registry.npmjs.org

    # 必要なモジュールをインストール
    - name: install node_modules
      run: npm ci

    # Prettier のフォーマット漏れがないかチェックする
    # ESlint のフォーマット漏れがないかチェックする
    - name: Code Format
      run: npm run format:check

    # TypeScripe エラーがないかチェックする
    # Coverage が100%であるかチェックする
    - name: Test
      uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        test-script: npm run test:coverage
        threshold: 100 # 'Coverage threshold. If total coverage is less than threshold 100%, PR will be rejected'
