on:
  push:
    branches:
      - develop
  workflow_dispatch:

name: Build and Preview Release
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: asia-northeast1
  REPOSITORY: cloud-run-source-release
  SERVICE_NAME_SUFFIX: release-

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout spelieve-secret
        uses: actions/checkout@v3
        with:
          repository: Ayato-kosaka/spelieve-secret
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: spelieve-secret

      - name: set env file
        run: 'mv ./spelieve-secret/spelieve-backend/release/.env ./'

      - name: delete spelieve-secret
        run: 'rm -rf spelieve-secret/'

      - uses: benjlevesque/short-sha@v2.1
        id: short-sha

      - name: set env
        run: echo "SERVICE_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}$SERVICE_NAME_SUFFIX/}" >> $GITHUB_ENV

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: github-action@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authorize Docker push
        run: gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Build Docker image
        run: docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE_NAME:${{ env.SHA }} .

      - name: Push Docker Image
        run: docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE_NAME:${{ env.SHA }}

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy $SERVICE_NAME \
            --project=$PROJECT_ID \
            --image=$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE_NAME:${{ env.SHA }} \
            --region=$REGION \
            --service-account=github-action@$PROJECT_ID.iam.gserviceaccount.com \
            --allow-unauthenticated \
            --revision-suffix=${{ env.SHA }}